export const dependencyCatalog = {
  react: '^19.2.4',
  'react-dom': '^19.2.4',
  next: '^16.1.6',
  typescript: '^5.9.3',
  '@types/react': '^19.2.14',
  '@types/react-dom': '^19.2.3',
  '@types/node': '^25.3.3',
  tailwindcss: '^4.2.1',
  postcss: '^8.5.8',
  autoprefixer: '^10.4.27',
  'drizzle-orm': '^0.45.1',
  'drizzle-kit': '^0.31.9',
  'better-auth': '^1.5.3',
  '@neondatabase/serverless': '^1.0.2',
  'class-variance-authority': '^0.7.1',
  clsx: '^2.1.1',
  'tailwind-merge': '^3.5.0',
  'tw-animate-css': '1.3.6',
  '@tailwindcss/postcss': '^4',
  zod: '^4.3.0',
  'lucide-react': '^0.575.0',
  '@hookform/resolvers': '^3.10.0',
  'react-hook-form': '^7.54.0',
} as const;

export const SHADCN_COMPONENTS = [
  'alert',
  'avatar',
  'badge',
  'button',
  'card',
  'dropdown-menu',
  'form',
  'input',
  'label',
  'separator',
  'sheet',
  'sidebar',
  'skeleton',
  'table',
  'tooltip',
] as const;
